UNIZAR-30226-2021-07/backend

- .github/workflows/ci.yaml
- tests/test_model.py
No estoy muy seguro aún de cómo haremos los tests por el momento así que lo dejo así (posiblemente no hace falta el `up -d`).
> Continuous Integration

- .env.example
- .github/workflows/ci.yaml
- .gitmodules
- README.md
- gatovid/api/data.py
- gatovid/create_db.py
- gatovid/exts.py
- gatovid/models.py
- setup.py
Closes #2
Para testearlo tendrás que hacer build, resetear la BBDD y volverla a crear.
Esto debería mergearse después de https://github.com/UNIZAR-30226-2021-07/assets/pull/1 porque sino la lectura de JSON falla (me  tendrás que dejar que descomente un par de líneas).
> Modelos de la base de datos

- LICENSE
A partir de la discusión en https://github.com/UNIZAR-30226-2021-07/documentacion/issues/16
> Creación de Licencia

- .github/workflows/ci.yaml
- gatovid/api/data.py
- gatovid/app.py
- gatovid/config.py
- gatovid/exts.py
- gatovid/models.py
- setup.py
- tests/base.py
- tests/test_sessions.py
> jwt management

- gatovid/api/__init__.py
- gatovid/api/data.py
- gatovid/create_db.py
- gatovid/models.py
- tests/base.py
- tests/test_sessions.py
- tests/test_user.py
> Codigos de error

- gatovid/api/game.py
- gatovid/game/__init__.py
- gatovid/game/cards.py
- gatovid/match.py
- gatovid/models.py
El tema de las acciones es para un supuesto patron command pero realmente no hay nada de eso establecido aun. Lo dejo porque la estructura seria similar igualmente, y ya lo miraremos mas adelante. Un problemilla que he tenido es que me daba una dependencia circular por el type hinting asi que he tenido que hacer una ñapa y ya lo arreglare en el futuro o si se te ocurre otra forma.
Lo que si que he podido estructurar un poco es el tema de `Game` y player, y creo que `Match` es bastante mas legible así.
> Estadísticas y algunas mejoras

- gatovid/api/data.py
- gatovid/api/game.py
- gatovid/app.py
- gatovid/game/__init__.py
- gatovid/match.py
* Arregla algunas cosas (de mi PR mayoritariamente y no el tuyo, porque no lo habia probado aun)
* Hace privados algunos miembros de las clases y funciones de modulos con los que no se deberia interactuar directamente
> Arreglos antes de mergear matchmaking

- .env.example
Sino ni los logs ni el live reload van bien.
> Usar DEBUG=True para pruebas internas

- gatovid/api/data.py
- gatovid/models.py
- tests/test_user.py
Tambien añade errores mas descriptivos
> Arregla error inesperado al asignar un nombre no unico

- docs/src/api-data.rst
- docs/src/api-game.rst
- docs/src/conf.py
- gatovid/api/data.py
- gatovid/api/game.py
- gatovid/game/__init__.py
- gatovid/match.py
- setup.py
He configurado Sphinx para que podamos hacer diagramas y he puesto uno de prueba. También más docs para el juego principalmente, y diagramas para explicar el flujo del juego.
Arregla el juego para que se termine automaticamente tambien. Las estadisticas se actualizan desde `Game` en vez de `Match`.
> Más documentación y algunos arreglos

- gatovid/game/__init__.py
- gatovid/models.py
> Herencia en vez de composición para Player

- docs/src/index.rst
- gatovid/api/game/__init__.py
- gatovid/api/game/match.py
- gatovid/app.py
- tests/test_ws.py
* Documentación de los mensajes del API de juego
* Intentar unirse a partidas cuando estás buscando una ya o estás en una privada devuelve error, de forma más consistente, y amplía los tests para probarlo.
No toco más código para que no se haga muy grande; solo hice lo del error porque me di cuenta haciendo los docs.
> Documentación, arreglos misceláneos

- docs/src/api-game.rst
- gatovid/api/game/match.py
- setup.py
> No usa caracteres ambigüos

- setup.py
Se supone que ya se ha resuelto: https://github.com/miguelgrinberg/python-socketio/issues/675
> Elimina workaround de dependencia que fallaba

- docs/src/api-game.rst
- gatovid/api/game/__init__.py
> stop_searching endpoint

- docs/src/api-game.rst
- format.sh
- gatovid/api/game/__init__.py
- gatovid/api/game/match.py
- gatovid/app.py
- gatovid/create_db.py
- gatovid/game/__init__.py
- gatovid/game/actions.py
- gatovid/game/body.py
- gatovid/game/cards.py
- gatovid/game/common.py
- tests/base.py
- tests/test_game.py
- tests/test_ws.py
Mira a ver el linter que se queja de algo que ha hecho el formatter.
> Manejo de cartas, cuerpo y pilas de cartas

- docs/src/api-game.rst
- gatovid/game/__init__.py
- gatovid/game/actions.py
- gatovid/game/cards.py
- tests/test_game.py
Whoops, no pensé que me fueras a mergear #102. La cuestión es que después de hacer una PR me gusta hacerme una auto-review y no había tenido tiempo para ello. No solo son mejoras de limpieza, sino que habia alguna cagada que me faltaba (no estaba sumando el turno, por ejemplo xd).
> Mejoras pequeñas

- docs/src/api-game.rst
- gatovid/api/game/__init__.py
- gatovid/api/game/match.py
- gatovid/game/__init__.py
- tests/base.py
- tests/test_game.py
> Sistema de pausa

- gatovid/api/game/__init__.py
- gatovid/api/game/match.py
- gatovid/game/__init__.py
- gatovid/game/actions.py
- gatovid/game/cards.py
- gatovid/util.py
- tests/base.py
- tests/test_cards.py
- tests/test_game.py
Como ya tenemos el sistema de turnos practicamente funcional, se va a probar el funcionamiento del juego
> Pruebas del juego en general

- gatovid/api/game/match.py
- gatovid/game/__init__.py
- gatovid/game/actions.py
- gatovid/game/cards.py
- gatovid/game/common.py
- gatovid/util.py
- tests/test_update.py
> class for GameUpdate

- gatovid/api/game/__init__.py
- gatovid/game/__init__.py
- gatovid/game/actions.py
- tests/base.py
- tests/test_game.py
> endpoint de play_discard y descarte automático

- gatovid/api/game/__init__.py
- gatovid/api/game/match.py
- tests/test_conn.py
- tests/test_ws.py
Closes #129 
Arregla un par de problemas de concurrencia y añade un test para revisar que funciona correctamente la cancelación.
> Test para join, arreglos de concurrencia

- docs/src/api-game.rst
- gatovid/api/game/__init__.py
- gatovid/api/game/match.py
- gatovid/game/__init__.py
- gatovid/game/common.py
- gatovid/models.py
- tests/base.py
- tests/test_conn.py
- tests/test_shop.py
- tests/test_ws.py
Closes #97
Closes #107
Depends on https://github.com/UNIZAR-30226-2021-07/assets/pull/20
> Sistema de reconexiones

- gatovid/game/__init__.py
- tests/base.py
- tests/test_conn.py
- tests/test_update.py
> Arreglo de pausa en abandono de partida

- docs/src/api-game.rst
- gatovid/api/game/__init__.py
- tests/test_conn.py
> Arreglos del sistema de reconexiones

- gatovid/api/game/__init__.py
- gatovid/game/body.py
- gatovid/game/cards.py
- tests/test_cards.py
> Tratamiento: Transplante

- gatovid/game/cards.py
La condicion hace que se puedan repetir organos del mismo color con que uno de los dos no tenga el color a transplantar. Con el `and` te aseguras de que estén los dos.
> fix transplante

- gatovid/api/game/__init__.py
- gatovid/game/cards.py
- gatovid/models.py
- tests/test_cards.py
- tests/test_game.py
- tests/test_ws.py
Nota mental: usar `type(x) is y` para checks de tipos básicos a partir de ahora...
Closes #139
> Arreglo de check de tipos básicos

- gatovid/game/cards.py
Evita casos en los que "Contagio" no hace nada
> Contagio estricto

- gatovid/game/__init__.py
- gatovid/game/cards.py
- tests/test_game.py
> Arregla algunas interacciones inválidas

- gatovid/game/__init__.py
> Mejores comprobaciones de victoria

- docs/src/api-game.rst
- gatovid/game/__init__.py
- gatovid/util.py
- tests/test_conn.py
> Tiempo restante al reconectar

- gatovid/game/__init__.py
- tests/test_game.py
> Cartas vuelven a la baraja tras ganar

- gatovid/api/game/match.py
- gatovid/game/__init__.py
> real timer values
